name: elogbook
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6
  flutter_switch: ^0.3.2
  provider: ^6.0.5
  sleek_circular_slider: ^2.0.1
  timeline_tile: ^2.0.0

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/vectors/

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: fonts/PlusJakartaSans-ExtraBold.ttf
        - asset: fonts/PlusJakartaSans-Bold.ttf
        - asset: fonts/PlusJakartaSans-SemiBold.ttf
        - asset: fonts/PlusJakartaSans-Medium.ttf
        - asset: fonts/PlusJakartaSans-Regular.ttf
        - asset: fonts/PlusJakartaSans-Light.ttf
        - asset: fonts/PlusJakartaSans-ExtraLight.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/launcher_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
