name: elogbook
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6
  flutter_switch: ^0.3.2
  grouped_list: ^5.1.2
  percent_indicator: ^4.2.3
  pie_chart: ^5.3.2
  provider: ^6.0.5
  semicircle_indicator: ^1.1.1
  sleek_circular_slider: ^2.0.1
  flutter_bloc: ^8.1.3
  timeago: ^3.4.0
  timeline_tile: ^2.0.0
  json_annotation: ^4.8.1
  get_it: ^7.6.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  dio: ^5.2.1+1
  flutter_native_splash: ^2.3.1


dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.0
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/vectors/

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: fonts/PlusJakartaSans-ExtraBold.ttf
        - asset: fonts/PlusJakartaSans-Bold.ttf
        - asset: fonts/PlusJakartaSans-SemiBold.ttf
        - asset: fonts/PlusJakartaSans-Medium.ttf
        - asset: fonts/PlusJakartaSans-Regular.ttf
        - asset: fonts/PlusJakartaSans-Light.ttf
        - asset: fonts/PlusJakartaSans-ExtraLight.ttf


flutter_native_splash:
  color: "#29C5F6"
  image: assets/icons/splash_logo.png
  color_dark: "#29C5F6"
  image_dark: assets/icons/splash_logo.png
  
  android_12:
    image: assets/icons/splash_logo.png
    icon_background_color: "#29C5F6"
    image_dark: assets/icons/splash_logo.png
    icon_background_color_dark: "#29C5F6"
  web: false
  android: true
  ios: true
