name: supervisor
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: ">=3.1.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6
  sleek_circular_slider: ^2.0.1
  flutter_bloc: ^8.1.3
  pie_chart: ^5.3.2
  semicircle_indicator: ^1.1.1
  form_builder_validators: ^9.0.0
  flutter_form_builder: ^9.1.0
  permission_handler: ^10.4.3
  intl: ^0.18.1
  device_info_plus: ^9.0.3
  file_picker: ^5.3.3
  flutter_rating_bar: ^4.0.1
  uuid: ^3.0.5
  grouped_list: ^5.1.2
  timeago: ^3.4.0
  pdf: ^3.10.4
  image_cropper: ^5.0.0
  timeline_tile: ^2.0.0
  percent_indicator: ^4.2.3
  flutter_switch: ^0.3.2
  countup: ^0.1.4
  file_saver: ^0.2.8
  path: ^1.8.3
  path_provider: ^2.0.5

  # Modul
  data:
    path: ../data
  core:
    path: ../core
  main:
    path: ../main
  common:
    path: ../common
  cool_alert: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
