name: common
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: ">=3.1.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6
  flutter_bloc: ^8.1.3
  intl: ^0.18.1
  path: ^1.8.3
  path_provider: ^2.0.5
  timeline_tile: ^2.0.0
  flutter_form_builder: ^9.1.0
  form_builder_validators: ^9.0.0
  url_launcher: ^6.1.13
  device_info_plus: ^9.0.3
  file_picker: ^5.5.0
  permission_handler: ^10.4.5

  # Modul
  data:
    path: ../data
  core:
    path: ../core
  main:
    path: ../main
  supervisor:
    path: ../supervisor
  coordinator:
    path: ../coordinator
  students:
    path: ../students
  pdf: ^3.10.7
  file_saver: ^0.2.9
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
