name: Flutter CI

on:
  push:
    branches:
      - main # ganti dengan branch default Anda
  pull_request:
    branches:
      - main # ganti dengan branch default Anda

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.10.0' # ganti dengan versi Flutter yang Anda gunakan

    - name: Install dependencies
      run: flutter pub get

    - name: Build Android APK
      run: flutter build apk --release

    - name: Build iOS IPA
      run: flutter build ios --release --no-codesign

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: |
          build/app/outputs/flutter-apk/app-release.apk
          build/ios/ipa/Runner.ipa
